/* eslint-disable camelcase,prefer-arrow-callback,no-plusplus,comma-dangle,no-loop-func,no-undef */
let capabilityApisPromise;

const loadCapabilityApis = async (config) => {
  try {
    if (capabilityApisPromise) {
      await capabilityApisPromise;
      return;
    }
    const capabilityApisCSS = document.createElement('link');
    const prefix = (config.prefix !== '') ? `/${config.prefix}` : '';
    const ticket = (config.ticket !== '' && config.ticket !== undefined) ? `?qlikTicket=${config.ticket}` : '';
    capabilityApisCSS.href = `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}/resources/autogenerated/qlik-styles.css${ticket}`;
    capabilityApisCSS.type = 'text/css';
    capabilityApisCSS.rel = 'stylesheet';
    document.head.appendChild(capabilityApisCSS);
    capabilityApisCSS.loaded = new Promise((resolve) => {
      capabilityApisCSS.onload = () => { resolve(); };
    });

    await Promise.all([capabilityApisCSS.loaded]);

    const capabilityApisJS = document.createElement('script');
    capabilityApisJS.src = `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}/resources/assets/external/requirejs/require.js`;
    document.head.appendChild(capabilityApisJS);
    capabilityApisJS.loaded = new Promise((resolve) => {
      capabilityApisJS.onload = () => { resolve(); };
    });

    capabilityApisPromise = Promise.all([capabilityApisJS.loaded, capabilityApisCSS.loaded]);

    await capabilityApisPromise;
  } catch (error) {
    throw new Error(error);
  }
};

const qApp = async (config) => {
  try {
    await loadCapabilityApis(config);
    const prefix = (config.prefix !== '') ? `/${config.prefix}/` : '/';
    window.require.config({
      baseUrl: `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}resources`,
      paths: {
        qlik: `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}resources/js/qlik`,
      },
      config: {
        text: {
          useXhr() {
            return true;
          },
        },
      },
    });
    return new Promise((resolve) => {
      window.require(['js/qlik'], (qlik) => {
        const app = qlik.openApp(config.appId, { ...config, isSecure: config.secure, prefix });
        for (let i = 0; i < config.fields.length; i++) {
          console.log('field:', config.fields[i]);
          app.createList({
            qDef: {
              qFieldDefs: [config.fields[i]], // set fieldname
            },
            qAutoSortByState: {
              qDisplayNumberOfRows: 1,
            },
            qInitialDataFetch: [{
              qHeight: 1000, // can set number of rows returned
              qWidth: 1,
            }],
          }, (reply) => {
            // console.log('reply:', reply.qListObject, 'app:', app.id);
            let rows = [];
            if (reply.qListObject.qDataPages.length > 0) {
              console.log('reply:', JSON.stringify(reply.qListObject.qDataPages[0].qMatrix), 'app:', app.id);
              rows = _.flatten(reply.qListObject.qDataPages[0].qMatrix);
            }
            const selected = rows.filter(row => row.qState === 'S');
            const values = [];
            for (let j = 0; j < selected.length; j++) {
              values.push(selected[j].qText);
            }

            // localStorage.setItem(reply.qListObject.qDimensionInfo.qFallbackTitle, JSON.stringify(values));
            const fieldName = reply.qListObject.qDimensionInfo.qFallbackTitle;
            if (localStorage.getItem(fieldName) !== JSON.stringify(values)) {
              console.log('local storage =', localStorage.getItem(fieldName), 'values =', JSON.stringify(values));
              localStorage.setItem(fieldName, JSON.stringify(values));
            }
          });
        }
        resolve(app);
      });
    });
  } catch (error) {
    throw new Error(error);
  }
};

export default qApp;
